version: "3.8"

services:
  meilisearch:
    image: getmeili/meilisearch
    container_name: meilisearch
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: "dev_key"
    volumes:
      - ./meili_data:/meili_data
